# Generated by Django 2.2 on 2020-08-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0003_auto_20200808_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
