# Generated by Django 2.2 on 2020-08-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0004_auto_20200809_0438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Customer',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
