# Generated by Django 2.2 on 2020-08-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0005_auto_20200809_1353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
