# Generated by Django 2.2 on 2020-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('book', models.CharField(max_length=50)),
            ],
        ),
    ]
